# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
# https://sw.kovidgoyal.net/kitty/conf.html

include font.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance.conf
include bell.conf
include window.conf
include tab.conf
include color.conf
include advanced.conf
include macos.conf
include keyboard.conf
