#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

## global settings
yabai -m config external_bar all:24:0
yabai -m config layout bsp
# yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.85
yabai -m config split_ratio 0.50
yabai -m config split_type vertical
yabai -m config auto_balance off

yabai -m space 5 --layout stack

## spacing
WINDOW_PADDING=5
yabai -m config top_padding ${WINDOW_PADDING}
yabai -m config bottom_padding ${WINDOW_PADDING}
yabai -m config left_padding ${WINDOW_PADDING}
yabai -m config right_padding ${WINDOW_PADDING}
yabai -m config window_gap ${WINDOW_PADDING}

function yabai_rule {
  yabai -m rule --add "$@"
  yabai -m rule --apply "$@"
}

## windows
yabai_rule app="^Code$"                space=1 manage=on
yabai_rule app="^IntelliJ IDEA$"       space=1 manage=off sub-layer=below
yabai_rule app="^Arc$"                 space=2 manage=on
yabai_rule app="^Google Chrome$"       space=2 manage=on
yabai_rule app="^Firefox$"             space=2 manage=on
yabai_rule app="^Slack$"               space=3 manage=on
yabai_rule app="^Discord$"             space=3 manage=on
yabai_rule app="^kitty$"               space=4 manage=on
yabai_rule app="^WezTerm$"             space=4 manage=on
yabai_rule app="^Microsoft Outlook$"   space=5 manage=on
yabai_rule app="^Obsidian$"            space=5 manage=on
yabai_rule app="^Brave Browser$"       space=6 manage=on
yabai_rule app="^PhpStorm$"            space=6 manage=on

## floating windows
yabai_rule app="^System Settings$"         manage=off sub-layer=above
yabai_rule app="^Finder$"                  manage=off sub-layer=above
yabai_rule app="^Shottr$"                  manage=off sub-layer=above
yabai_rule app="^Kap$"                     manage=off sub-layer=above
yabai_rule app="^Docker Desktop$"          manage=off sub-layer=above

yabai_rule title="^Playwright Test$"               manage=off sub-layer=below
yabai_rule title="^Playwright Trace Viewer$"       manage=off sub-layer=below

yabai_rule app="^Disk Utility$"            manage=off sub-layer=below
yabai_rule app="^System Information$"      manage=off sub-layer=below
yabai_rule app="^Activity Monitor$"        manage=off sub-layer=below
yabai_rule app="^TeamViewer$"              manage=off sub-layer=below
yabai_rule app="^java$"                    manage=off sub-layer=below
yabai_rule app="^Calculator$"              manage=off sub-layer=below
yabai_rule app="^Karabiner-Elements$"      manage=off sub-layer=below
yabai_rule app="^Karabiner-EventViewer$"   manage=off sub-layer=below

yabai_rule app="^KeePassXC$" display=1 manage=off grid=7:7:1:1:5:5 sub-layer=below
yabai_rule app="^Bitwarden$"           manage=off grid=7:7:1:1:5:5 sub-layer=below
yabai_rule app="^Arc$" title="^$"      manage=off
