#!/usr/bin/env bash

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      25
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "feather:Regular:14.0"

spacebar -m config power_icon_strip    
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffffa500

spacebar -m config space_icon         
spacebar -m config space_icon_strip        
spacebar -m config space_icon_color   0xff458588

spacebar -m config clock_icon         
spacebar -m config clock_icon_color   0xff4fe2ff
spacebar -m config clock_format       "%d.%m.%Y      %R"


echo "spacebar configuration loaded.."
